# -*- coding: utf-8 -*-
"""data_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lwcQIBySGoluC9Bcva-nshHBrJNYcmpK
"""

import streamlit as st
import pandas as pd

def app():

    # --------------------------------------------------
    # Page Title
    # --------------------------------------------------
    st.title("🧹 Data Preprocessing")
    st.markdown(
        """
        This page explains **how the raw air quality data was cleaned and prepared**
        before performing exploratory data analysis and visualization.
        """
    )

    # --------------------------------------------------
    # Load Data
    # --------------------------------------------------
    @st.cache_data
    def load_data():
        return pd.read_csv("preprocessed_aqi_dataset_20251217.csv")

    df = load_data()
    df['Date'] = pd.to_datetime(df['Date'])

    # --------------------------------------------------
    # Dataset Shape
    # --------------------------------------------------
    st.subheader("📊 Dataset Size After Preprocessing")

    col1, col2 = st.columns(2)
    with col1:
        st.metric("Total Records", f"{len(df):,}")
    with col2:
        st.metric("Total Columns", df.shape[1])

    # --------------------------------------------------
    # Missing Values Check
    # --------------------------------------------------
    st.subheader("🔍 Missing Value Validation")

    missing = df.isna().sum()
    st.dataframe(missing)

    st.success("✅ No missing values remain after preprocessing.")

    # --------------------------------------------------
    # Preprocessing Steps Explained
    # --------------------------------------------------
    st.subheader("🛠️ Preprocessing Steps Applied")

    st.markdown(
        """
        **1️⃣ Date Conversion**
        - Converted the `Date` column into datetime format
        - Enabled time-series and seasonal analysis

        **2️⃣ Numerical Missing Values (Median Imputation)**
        - Applied to pollutants like PM2.5, PM10, NO₂, CO, AQI, etc.
        - Median was chosen to reduce the impact of extreme pollution values

        **3️⃣ Categorical Missing Values (Mode Imputation)**
        - Applied to `AQI_Bucket`
        - Preserves the most frequent air-quality category

        **4️⃣ Final Validation**
        - Confirmed that all missing values were handled
        - Saved the cleaned dataset for further analysis
        """
    )

    # --------------------------------------------------
    # Show Sample Data
    # --------------------------------------------------
    st.subheader("📄 Sample of Cleaned Data")

    st.dataframe(df.head(10))

    # --------------------------------------------------
    # Why This Matters
    # --------------------------------------------------
    st.subheader("🌱 Why Preprocessing Matters")

    st.markdown(
        """
        Proper preprocessing ensures:
        - 📉 Reduced bias from outliers
        - 📊 More reliable visualizations
        - 🤖 Better performance in ML models
        - 🧠 Trustworthy insights and conclusions
        """
    )