# -*- coding: utf-8 -*-
"""home.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DQ9UTxWYXaj03N9RdwodyyjvY-P2S9pH
"""

import streamlit as st

# --------------------------------------------------
# Page config (MUST be outside app())
# --------------------------------------------------
st.set_page_config(
    page_title="India Air Quality Analysis (2015–2020)",
    page_icon="🌍",
    layout="wide"
)

def app():

    # --------------------------------------------------
    # Title
    # --------------------------------------------------
    st.title("🌫️ India Air Quality Analysis (2015–2020)")

    st.markdown(
        """
        ### Welcome 👋
        This interactive dashboard provides insights into **air pollution levels across India**
        using data collected between **2015 and 2020**.

        The application helps users understand:
        - How air quality has changed over time
        - Which cities are most polluted
        - Which pollutants contribute the most to poor air quality
        - Seasonal and monthly pollution patterns

        ---
        """
    )

    # --------------------------------------------------
    # Dataset Overview
    # --------------------------------------------------
    st.subheader("📂 Dataset Overview")

    st.markdown(
        """
        - **Source:** Central Pollution Control Board (CPCB), India
        - **Time Period:** 2015 – 2020
        - **Coverage:** Multiple Indian cities and monitoring stations
        - **Key Metrics:**
            - AQI (Air Quality Index)
            - PM2.5, PM10
            - NO, NO₂, NOx
            - SO₂, CO, O₃
            - AQI Categories (Good, Moderate, Poor, etc.)
        """
    )

    # --------------------------------------------------
    # Why This Matters
    # --------------------------------------------------
    st.subheader("🌱 Why This Analysis Matters")

    st.markdown(
        """
        Air pollution is one of the most serious environmental challenges in India.
        Understanding air quality trends helps:
        - 🏛️ Policymakers design better regulations
        - 🔬 Researchers study pollution patterns
        - 👥 Citizens become aware of environmental risks
        - 🌍 Organizations plan sustainable solutions
        """
    )

    # --------------------------------------------------
    # Navigation