# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1byC3GnOlRfu-ageKfhrJyAPlyTzhJA8h
"""

import streamlit as st
from multiapp import MultiApp

#from app import calculator,bmi
import home
import data_preprocessing
import eda
import model_building

app = MultiApp()

# Add all your application here
#app.add_app("Data page for demo", data.app)
app.add_app("Home", home.app)
app.add_app("Data Preprocessing", data_preprocessing.app)
app.add_app("eda".eda.app)
app.add_app("Model Building", model_building.app)

# The main app
app.run()