# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1byC3GnOlRfu-ageKfhrJyAPlyTzhJA8h
"""

import streamlit as st
from multiapp import MultiApp

import home
import data_preprocessing
import eda
import model_building

app = MultiApp()

app.add_app("Home", home.app)
app.add_app("Data Preprocessing", data_preprocessing.app)
app.add_app("EDA", eda.app)
app.add_app("Model Building", model_building.app)

app.run()