# -*- coding: utf-8 -*-
"""model_building.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FN1Q0PZ_piEm1TZI6Payy8XP9dRvZQGD
"""

import streamlit as st
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

def app():

    # --------------------------------------------------
    # Page Title
    # --------------------------------------------------
    st.title("🤖 Model Building – AQI Prediction")
    st.markdown(
        """
        This page demonstrates how a **machine learning model** is built
        to **predict Air Quality Index (AQI)** using pollutant concentrations.
        """
    )

    # --------------------------------------------------
    # Load Data
    # --------------------------------------------------
    @st.cache_data
    def load_data():
        return pd.read_csv("preprocessed_aqi_dataset_20251217.csv")

    df = load_data()

    # --------------------------------------------------
    # Feature Selection
    # --------------------------------------------------
    st.subheader("🧩 Feature Selection")

    st.markdown(
        """
        **Target Variable:** AQI
        **Input Features:** Major air pollutants
        """
    )

    features = [
        'PM2.5', 'PM10', 'NO', 'NO2', 'NOx',
        'NH3', 'CO', 'SO2', 'O3'
    ]

    X = df[features]
    y = df['AQI']

    st.write("Selected Features:")
    st.write(features)

    # --------------------------------------------------
    # Train-Test Split
    # --------------------------------------------------
    st.subheader("✂️ Train-Test Split")

    test_size = st.slider("Select Test Size (%)", 20, 40, 25) / 100

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=test_size, random_state=42
    )

    st.write(f"Training Samples: {len(X_train)}")
    st.write(f"Testing Samples: {len(X_test)}")

    # --------------------------------------------------
    # Model Training
    # --------------------------------------------------
    st.subheader("🌲 Model Training")

    n_estimators = st.slider("Number of Trees (n_estimators)", 50, 300, 100)

    model = RandomForestRegressor(
        n_estimators=n_estimators,
        random_state=42,
        n_jobs=-1
    )

    model.fit(X_train, y_train)

    st.success("✅ Model trained successfully!")

    # --------------------------------------------------
    # Model Evaluation
    # --------------------------------------------------
    st.subheader("📊 Model Evaluation")

    y_pred = model.predict(X_test)

    mae = mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    r2 = r2_score(y_test, y_pred)

    col1, col2, col3 = st.columns(3)
    with col1:
        st.metric("MAE", round(mae, 2))
    with col2:
        st.metric("RMSE", round(rmse, 2))
    with col3:
        st.metric("R² Score", round(r2, 3))

    # --------------------------------------------------
    # Feature Importance
    # --------------------------------------------------
    st.subheader("⭐ Feature Importance")

    importance_df = pd.DataFrame({
        "Feature": features,
        "Importance": model.feature_importances_
    }).sort_values(by="Importance", ascending=False)

    st.bar_chart(importance_df.set_index("Feature"))

    st.markdown(
        """
        👉 Feature importance shows which pollutants contribute most
        to predicting AQI.
        """
    )

    # --------------------------------------------------
    # Interpretation
    # --------------------------------------------------
    st.subheader("🧠 Model Interpretation")

    st.markdown(
        """
        - The Random Forest model captures **non-linear relationships**
        - PM2.5 and PM10 usually emerge as the strongest predictors
        - High R² indicates good explanatory power
        """
    )