# -*- coding: utf-8 -*-
"""multipage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17OGgW_7l79ih_j_KFNBH_5y6_LN00hnf
"""

# multiapp.py
import streamlit as st

class MultiApp:
    def __init__(self):
        self.apps = []

    def add_app(self, title, func):
        self.apps.append({
            "title": title,
            "function": func
        })

    def run(self):
        app = st.sidebar.selectbox(
            'Select your choice from drop down list',
            self.apps,
            format_func=lambda app: app['title'])

        app['function']()